# Generated by Django 2.2.5 on 2019-11-04 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_status', models.CharField(choices=[('DN', 'New'), ('DO', 'Open'), ('DR', 'Rejected'), ('DF', 'Fixed'), ('DC', 'Closed')], default='DN', max_length=2)),
                ('defect_type', models.CharField(choices=[('CO', 'Configuration'), ('TE', 'Tester Error'), ('UI', 'User Interface'), ('OT', 'OTHER')], default='CO', max_length=2)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='', max_length=4)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defect_manager_app.Defect')),
            ],
        ),
    ]
