# Generated by Django 2.2.5 on 2019-11-13 01:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('defect_status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Fixed', 'Fixed'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('defect_type', models.CharField(choices=[('Configuration', 'Configuration'), ('Tester Error', 'Tester Error'), ('User Interface', 'User Interface'), ('Other', 'OTHER')], default='Configuration', max_length=64)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='', max_length=8)),
                ('name', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField()),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defect_manager_app.Defect')),
            ],
        ),
    ]
