# Generated by Django 2.2.5 on 2019-11-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defect_manager_app', '0002_defect_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='title',
            new_name='name',
        ),
    ]
