# Generated by Django 2.2.5 on 2019-11-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect_manager_app', '0003_auto_20191104_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Rejected', 'Rejected'), ('Fixed', 'Fixed'), ('Closed', 'Closed')], default='New', max_length=2),
        ),
    ]
